export const profile = {
  name: 'Ronald Barnhart',
  role: 'Product Engineer',
  location: 'Austin, TX',
  links: {
    github: 'https://github.com/AgentBurgundy?tab=repositories',
    firesaasRepo: 'https://github.com/AgentBurgundy/fire-saas',
    vldt: 'https://www.vldt.ai/',
    wellspring: 'https://apps.apple.com/us/app/wellspring-daily-devotionals/id6741737201',
    practiceInterview: 'https://practiceinterview.ai/',
    firesaas: 'https://firesaas.dev/',
    stanly: 'https://stanly.io/',
    website: 'https://aibaker.io',
    resume: '/Ronald Barnhart - Resume.pdf',
  },
  highlights: [
    'Customer-facing apps with premium UX',
    'Greenfield 0→1 builds (fast iteration, clean foundations)',
    'Full-stack TypeScript: React + Node + Postgres',
  ],
  featuredProjects: [
    {
      name: 'Validate AI (vldt.ai)',
      tagline: 'Validate SaaS ideas in minutes with AI',
      kind: 'Web app',
      stack: ['TypeScript', 'React', 'AI', 'Product'],
      url: 'https://www.vldt.ai/',
      previewImage: '/previews/vldt.png',
      note: 'Built end-to-end: product UX, landing flow, and the “ship it” pipeline.',
    },
    {
      name: 'FireSaaS (firesaas.dev)',
      tagline: 'Open-source framework for Next.js + Firebase apps',
      kind: 'Open source',
      stack: ['Next.js', 'Firebase', 'TypeScript', 'SaaS'],
      url: 'https://firesaas.dev/',
      previewImage: '/previews/firesaas.png',
      repoUrl: 'https://github.com/AgentBurgundy/fire-saas',
      note: 'Framework + boilerplate to ship SaaS apps quickly with modern defaults and clean structure.',
    },
    {
      name: 'PracticeInterview.ai',
      tagline: 'AI mock interviews with your real voice',
      kind: 'Web app',
      stack: ['TypeScript', 'AI', 'Whisper', 'ChatGPT'],
      url: 'https://practiceinterview.ai/',
      previewImage: '/previews/practiceinterview.png',
      note: 'Mock interview platform using voice input (Whisper) so users can answer questions naturally and practice under real conditions.',
    },
    {
      name: 'Vericuda Training (training.vericuda.com)',
      tagline: 'E-learning platform for manufacturing employees (contract)',
      kind: 'Web app',
      stack: ['React', 'TypeScript', 'Customer-facing', 'E-learning'],
      url: 'https://training.vericuda.com',
      previewImage: '/previews/vericuda-training.png',
      note: 'Contract build for Vericuda: training experience for manufacturing teams with a clean, practical UX.',
    },
    {
      name: 'Wellspring',
      tagline: 'Daily devotionals (React Native, iOS + Android)',
      kind: 'Mobile app',
      stack: ['React Native', 'TypeScript', 'Mobile', 'Subscriptions'],
      url: 'https://apps.apple.com/us/app/wellspring-daily-devotionals/id6741737201',
      previewImage: '/previews/wellspring.png',
      note: 'Cross-platform experience with a calm, polished interface and strong iteration cadence.',
    },
    {
      name: 'Stanly (stanly.io)',
      tagline: 'Founder-style abandoned cart recovery',
      kind: 'Web app',
      stack: ['React', 'TypeScript', 'Customer-facing', 'Landing'],
      url: 'https://stanly.io/',
      previewImage: '/previews/stanly.png',
      note: 'Customer-facing landing + product positioning for Stanly. Built to convert and communicate clearly.',
    },
  ],
} as const

