export const profile = {
  name: "Ronald Barnhart",
  role: "Founder & Engineer",
  location: "Austin, TX",
  links: {
    github: "https://github.com/AgentBurgundy?tab=repositories",
    firesaasRepo: "https://github.com/AgentBurgundy/fire-saas",
    vldt: "https://www.vldt.ai/",
    wellspring:
      "https://apps.apple.com/us/app/wellspring-daily-devotionals/id6741737201",
    practiceInterview: "https://practiceinterview.ai/",
    firesaas: "https://firesaas.dev/",
    stanly: "https://stanly.io/",
    manacrypt: "https://manacrypt.gg",
    biobattler: "https://biobattler.com",
    website: "https://aibaker.io",
    resume: "/Ronald Barnhart - Resume.pdf",
  },
  highlights: [
    "Founder & engineer -- I build and ship entire products",
    "Full-stack TypeScript: React, Node, Postgres, AI",
    "0->1 specialist -- idea to production, fast",
  ],
  featuredProjects: [
    {
      name: "vldt.ai",
      tagline: "AI-powered startup idea validation",
      kind: "SaaS",
      role: "Founder",
      stack: ["Next.js", "React", "OpenAI", "Postgres", "Tailwind"],
      url: "https://www.vldt.ai/",
      previewImage: "/previews/vldt.png",
      note: "Ingests a raw idea and generates a full design doc, competitor landscape, and landing page flow using chained GPT-4 calls. Built the entire product solo -- prompt engineering, API layer, UI, and deployment.",
    },
    {
      name: "stanly.io",
      tagline: "Agentic abandoned cart recovery for Shopify",
      kind: "SaaS",
      role: "Founder",
      stack: ["Node.js", "OpenAI", "Redis", "BullMQ", "Shopify API", "React"],
      url: "https://stanly.io/",
      previewImage: "/previews/stanly.png",
      note: "Autonomous AI agents handle incoming email replies using a ReAct pattern -- reasoning about customer objections, calling Shopify APIs for product lookups and discount generation, then drafting and self-reviewing responses before sending. Processes thousands of automated interactions daily.",
    },
    {
      name: "wellspring",
      tagline: "Daily devotionals app -- iOS & Android",
      kind: "Mobile",
      role: "Founder",
      stack: ["React Native", "Expo", "TypeScript", "Node.js"],
      url: "https://apps.apple.com/us/app/wellspring-daily-devotionals/id6741737201",
      previewImage: "/previews/wellspring.png",
      note: "Cross-platform React Native app with offline-first architecture, smooth gesture-driven animations, and subscription billing. Shipped to both app stores with fast iteration cycles driven by real user feedback.",
    },
    {
      name: "practiceinterview.ai",
      tagline: "Voice-to-voice AI mock interviews",
      kind: "Web app",
      role: "Founder",
      stack: ["React", "TypeScript", "OpenAI Whisper", "GPT-4", "WebSockets"],
      url: "https://practiceinterview.ai/",
      previewImage: "/previews/practiceinterview.png",
      note: "Real-time speech transcription via Whisper piped into GPT-4 for dynamic follow-up question generation. Achieved <800ms conversational latency. Designed the UX to mimic the pressure of a real interview -- no buttons, just talk.",
    },
    {
      name: "firesaas.dev",
      tagline: "Open-source Next.js + Firebase SaaS starter",
      kind: "OSS",
      role: "Founder",
      stack: ["Next.js", "Firebase", "TypeScript", "Stripe", "Tailwind"],
      url: "https://firesaas.dev/",
      previewImage: "/previews/firesaas.png",
      repoUrl: "https://github.com/AgentBurgundy/fire-saas",
      note: "Opinionated boilerplate with auth, Stripe billing, admin dashboard, and deploy config baked in. Designed so other developers can go from clone to production in hours instead of weeks.",
    },
    {
      name: "manacrypt.gg",
      tagline: "Sealed product price tracking for Magic: The Gathering",
      kind: "SaaS",
      role: "Founder",
      stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Tailwind"],
      url: "https://manacrypt.gg",
      previewImage: "/previews/manacrypt.png",
      note: "Price tracker for sealed MTG products -- booster boxes, collector editions, bundles. Aggregates pricing data, tracks trends over time, and helps collectors and investors make informed buying decisions.",
    },
    {
      name: "biobattler.com",
      tagline: "Competitive biology-themed battler game",
      kind: "Game",
      role: "Founder",
      stack: ["React", "TypeScript", "Canvas", "Node.js", "WebSockets"],
      url: "https://biobattler.com",
      previewImage: "/previews/biobattler.png",
      note: "Real-time competitive game with biology-themed mechanics. Custom game engine, multiplayer via WebSockets, matchmaking, and animated battle sequences.",
    },
    {
      name: "vericuda training",
      tagline: "E-learning platform for manufacturing teams",
      kind: "Contract",
      role: "Founder",
      stack: ["React", "TypeScript", "Node.js", "PostgreSQL"],
      url: "https://training.vericuda.com",
      previewImage: "/previews/vericuda-training.png",
      note: "Contract build for Vericuda -- employee training platform with course management, progress tracking, and role-based access. Focused on practical UX for non-technical users in manufacturing environments.",
    },
  ],
} as const;

export const resumeData = {
  name: "Ronald Barnhart",
  title: "Senior Product Engineer (0->1, AI, & Mobile)",
  location: "Austin, TX",
  phone: "(330) 814-4605",
  email: "ronald@aibaker.io",
  linkedin: "linkedin.com/in/ronaldbarnhart",
  github: "github.com/AgentBurgundy",
  website: "aibaker.io",

  summary:
    "Senior Product Engineer with 8+ years of experience specializing in greenfield (0->1) development and shipping user-centric products. A full-stack builder (React/Node/Postgres) who moves fast, sweats the UX details, and builds high-scale systems. Proven ability to architect event-driven backends processing millions of daily requests while delivering intuitive, premium frontend experiences.",

  featuredShipments: [
    {
      name: "Stanly.io",
      role: "Founder & Lead Engineer",
      mission: "Automated, agent-led abandoned cart recovery for e-commerce.",
      bullets: [
        "Agentic Architecture: Engineered an autonomous agent workflow that processes incoming email replies using a ReAct (Reason + Act) pattern.",
        "Tool Use & Orchestration: Built a system where the agent autonomously executes Shopify API calls (product lookups, dynamic discount generation) to resolve customer objections without human intervention.",
        'Self-Correction: Implemented a multi-step "Draft-Review-Send" pipeline where a secondary LLM layer audits drafted responses for tone and accuracy before delivery.',
        "Scale: Handles a high-throughput event pipeline processing millions of webhooks and thousands of automated agent interactions daily.",
      ],
    },
    {
      name: "vldt.ai (Validate AI)",
      role: "Founder & Lead Engineer",
      mission: "Automate the startup validation process using Generative AI.",
      bullets: [
        "Build: Engineered a full-stack engine that ingests user ideas and autonomously generates comprehensive design docs, competitor analyses, and landing page flows.",
        "Tech: Next.js, OpenAI API (Chain-of-Thought prompting), Postgres, Tailwind.",
      ],
    },
    {
      name: "Wellspring",
      role: "Mobile Developer",
      mission: "A consumer-facing React Native app for iOS and Android.",
      bullets: [
        "Build: Shipped a calm, high-performance mobile experience with a focus on smooth animations, offline-first capabilities, and fast iteration cycles based on real user feedback.",
        "Tech: React Native, Expo, Node.js backend.",
      ],
    },
    {
      name: "PracticeInterview.ai",
      role: "Product Engineer",
      mission:
        "Create a realistic interview simulator using voice-to-voice AI.",
      bullets: [
        "Build: Integrated OpenAI Whisper for real-time speech transcription and GPT-4 for dynamic context generation, achieving a conversational latency of <800ms.",
        'UX: Designed a seamless "hands-free" user interface that mimics the pressure and flow of a real interview environment.',
      ],
    },
  ],

  experience: [
    {
      title: "Senior Front End Software Engineer",
      company: "BambooHR",
      location: "Austin, TX (Remote)",
      when: "May 2022 - Present",
      bullets: [
        "Lead engineer on critical customer-facing HR workflows. Focused on high-fidelity UX implementation and performance, reducing load times by 25% through code-splitting and asset optimization.",
        'Spearheaded the internal adoption of AI tools (Copilot, Cursor), creating a "bias for action" culture that increased shipping velocity across the team.',
        "Architected reusable UI primitives and component libraries that ensure design consistency across a massive enterprise application.",
      ],
    },
    {
      title: "Senior Software Engineer",
      company: "Tensure Consulting",
      location: "Austin, TX",
      when: "May 2021 - May 2022",
      bullets: [
        "Acted as the technical lead for 0->1 enterprise builds. Translated ambiguous client needs into concrete technical specs and shipped full-stack solutions on Google Cloud.",
        "Established CI/CD pipelines and code quality standards, mentoring junior engineers on writing clean, reliable TypeScript.",
      ],
    },
    {
      title: "Software Engineer II",
      company: "S&P Global Market Intelligence",
      location: "Richmond, VA",
      when: "Dec 2018 - May 2021",
      bullets: [
        "Built complex, high-performance financial charting tools using D3.js and React for high-volume data feeds.",
        "Implemented end-to-end testing strategies (Cypress) that improved deployment confidence and reduced regression bugs by 40%.",
      ],
    },
    {
      title: "Software Developer",
      company: "Hyland",
      location: "Westlake, OH",
      when: "Jun 2017 - Nov 2018",
      bullets: [
        "Contributed to enterprise content management systems, building automation frameworks that reduced manual testing time by 50%.",
      ],
    },
  ],

  skills: {
    "Core Stack": [
      "TypeScript",
      "JavaScript (ES6+)",
      "React",
      "Next.js (App Router)",
      "Node.js",
      "HTML/CSS",
    ],
    "Scale & Infra": [
      "Redis (BullMQ)",
      "PostgreSQL",
      "Google Cloud (Pub/Sub)",
      "Docker",
      "Terraform",
      "Serverless functions",
    ],
    Mobile: ["React Native", "Expo", "iOS/Android deployment"],
    "AI Engineering": [
      "OpenAI API (GPT-4, Whisper)",
      "LangChain",
      "Vector Embeddings",
      "Prompt Engineering",
    ],
    Tools: ["Git", "GitHub Actions", "Figma (Design Systems)", "Vercel"],
  },
} as const;
